[package]
name = "neon"
version = "0.1.0"
edition = "2021"
description = "A toy language you didn't wait for"
repository = "https://github.com/patbuc/neon"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
colored = "3.0.0"
lazy_static = "1.5.0"
env_logger = "0.11.8"
log = "0.4.27"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
ordered-float = { version = "4.6.0", features = ["serde"] }
strsim = "0.11"
indexmap = "2.12.1"
cranelift-codegen = { version = "0.130", optional = true }
cranelift-frontend = { version = "0.130", optional = true }
cranelift-jit = { version = "0.130", optional = true }
cranelift-module = { version = "0.130", optional = true }
cranelift-native = { version = "0.130", optional = true }

[dev-dependencies]
datatest-stable = "0.3.3"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[[test]]
name = "neon_scripts"
harness = false

[features]
disassemble = []
opcode-stats = []
jit = ["dep:cranelift-codegen", "dep:cranelift-frontend", "dep:cranelift-jit", "dep:cranelift-module", "dep:cranelift-native"]

[lints.clippy]
print_stdout = "deny"
print_stderr = "deny"
unwrap_used = "deny"
expect_used = "deny"

[profile.release]
lto = "fat"
panic = "abort"
