/// One decoded instruction. Jump targets are absolute instruction indices;
/// `Closure.upvalues` is the start of its `(is_local, index)` run in
/// `Chunk::closure_upvalues`.
#[derive(Debug, Clone, Copy, PartialEq)]
#[allow(dead_code)]
pub(crate) enum Instr {
    Return,
    Constant(u16),
    Negate,
    Add,
    Subtract,
    Multiply,
    Divide,
    Modulo,
    Exponent,
    Nil,
    True,
    False,
    Equal,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    Not,
    Pop,
    SetLocal(u16),
    GetLocal(u16),
    JumpIfFalse(u32),
    Jump(u32),
    Loop(u32),
    Call(u8),
    Invoke {
        method_symbol: u16,
        arg_count: u8,
    },
    GetBuiltin(u16),
    GetGlobal(u16),
    SetGlobal(u16),
    GetField(u16),
    SetField(u16),
    GetLocalField {
        slot: u16,
        symbol: u16,
    },
    CreateMap(u16),
    CreateArray(u16),
    CreateSet(u16),
    GetIndex,
    SetIndex,
    GetIterator {
        pairs: bool,
    },
    IteratorNext(u16),
    IteratorDone(u16),
    CreateRange {
        inclusive: bool,
    },
    ToString,
    BitwiseAnd,
    BitwiseOr,
    BitwiseXor,
    BitwiseNot,
    LeftShift,
    RightShift,
    Closure {
        const_index: u16,
        upvalue_count: u8,
        upvalues: u32,
    },
    GetUpvalue(u16),
    SetUpvalue(u16),
    CloseUpvalue,
    DefineMethod {
        type_symbol: u16,
        method_symbol: u16,
        takes_self: bool,
    },
    DefineBuiltinMethod {
        type_symbol: u16,
        method_symbol: u16,
        takes_self: bool,
    },
    CheckInitialized,
    CheckTuple(u16),
    StoreLocal(u16),
    StoreField(u16),
    StoreLocalField {
        slot: u16,
        symbol: u16,
    },
    AddConstant(u16),
    SubtractConstant(u16),
    GreaterConstant(u16),
    GreaterEqualConstant(u16),
    LessConstant(u16),
    LessEqualConstant(u16),
    Dup,
    Dup2,
    JumpIfNotNil(u32),
    JumpIfNil(u32),
    NoMatchArm,
    EnumConstruct(u16),
    IsArrayOfLen {
        length: u16,
        at_least: bool,
    },
    IsVariant(u16),
    TailCall(u8),
    TailInvoke {
        method_symbol: u16,
        arg_count: u8,
    },
    IsNumber,
    /// A byte that is no opcode; executing it is a runtime error. Decoding
    /// stops here, since the width of what follows is unknown.
    Invalid(u8),
}
