#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 51
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 4

enum {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_val = 3,
  anon_sym_EQ = 4,
  anon_sym_var = 5,
  anon_sym_print = 6,
  anon_sym_PLUS = 7,
  anon_sym_DASH = 8,
  anon_sym_STAR = 9,
  anon_sym_SLASH = 10,
  anon_sym_BANG = 11,
  anon_sym_LPAREN = 12,
  anon_sym_RPAREN = 13,
  anon_sym_DQUOTE = 14,
  aux_sym_string_token1 = 15,
  aux_sym_string_token2 = 16,
  sym_number = 17,
  anon_sym_true = 18,
  anon_sym_false = 19,
  sym_nil = 20,
  sym_source_file = 21,
  sym_declaration = 22,
  sym_val_declaration = 23,
  sym_var_declaration = 24,
  sym_statement = 25,
  sym_expression_statement = 26,
  sym_print_statement = 27,
  sym_expression = 28,
  sym_binary_expression = 29,
  sym_unary_expression = 30,
  sym_primary_expression = 31,
  sym_string = 32,
  sym_boolean = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym_string_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_val] = "val",
  [anon_sym_EQ] = "=",
  [anon_sym_var] = "var",
  [anon_sym_print] = "print",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_BANG] = "!",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_nil] = "nil",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym_val_declaration] = "val_declaration",
  [sym_var_declaration] = "var_declaration",
  [sym_statement] = "statement",
  [sym_expression_statement] = "expression_statement",
  [sym_print_statement] = "print_statement",
  [sym_expression] = "expression",
  [sym_binary_expression] = "binary_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_primary_expression] = "primary_expression",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_val] = anon_sym_val,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_print] = anon_sym_print,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_nil] = sym_nil,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym_val_declaration] = sym_val_declaration,
  [sym_var_declaration] = sym_var_declaration,
  [sym_statement] = sym_statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym_print_statement] = sym_print_statement,
  [sym_expression] = sym_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_primary_expression] = sym_primary_expression,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_val] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_val_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_var_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_print_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_left = 1,
  field_name = 2,
  field_right = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_name] = "name",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_left, 0},
    {field_right, 2},
  [3] =
    {field_name, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 17,
  [21] = 21,
  [22] = 22,
  [23] = 18,
  [24] = 24,
  [25] = 25,
  [26] = 22,
  [27] = 19,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 9,
  [34] = 10,
  [35] = 14,
  [36] = 16,
  [37] = 4,
  [38] = 7,
  [39] = 6,
  [40] = 11,
  [41] = 8,
  [42] = 32,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 45,
  [47] = 44,
  [48] = 48,
  [49] = 49,
  [50] = 50,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '!') ADVANCE(11);
      if (lookahead == '"') ADVANCE(14);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '+') ADVANCE(7);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(14);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(18);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 3:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(5);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 'p') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (lookahead == 'v') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(15);
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_val);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_val] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(49),
    [sym_declaration] = STATE(3),
    [sym_val_declaration] = STATE(30),
    [sym_var_declaration] = STATE(30),
    [sym_statement] = STATE(30),
    [sym_expression_statement] = STATE(31),
    [sym_print_statement] = STATE(31),
    [sym_expression] = STATE(13),
    [sym_binary_expression] = STATE(14),
    [sym_unary_expression] = STATE(14),
    [sym_primary_expression] = STATE(14),
    [sym_string] = STATE(9),
    [sym_boolean] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_val] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(11),
    [anon_sym_print] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(7),
  },
  [2] = {
    [sym_declaration] = STATE(2),
    [sym_val_declaration] = STATE(30),
    [sym_var_declaration] = STATE(30),
    [sym_statement] = STATE(30),
    [sym_expression_statement] = STATE(31),
    [sym_print_statement] = STATE(31),
    [sym_expression] = STATE(13),
    [sym_binary_expression] = STATE(14),
    [sym_unary_expression] = STATE(14),
    [sym_primary_expression] = STATE(14),
    [sym_string] = STATE(9),
    [sym_boolean] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
    [anon_sym_val] = ACTIONS(30),
    [anon_sym_var] = ACTIONS(33),
    [anon_sym_print] = ACTIONS(36),
    [anon_sym_DASH] = ACTIONS(39),
    [anon_sym_BANG] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(42),
    [anon_sym_DQUOTE] = ACTIONS(45),
    [sym_number] = ACTIONS(48),
    [anon_sym_true] = ACTIONS(51),
    [anon_sym_false] = ACTIONS(51),
    [sym_nil] = ACTIONS(27),
  },
  [3] = {
    [sym_declaration] = STATE(2),
    [sym_val_declaration] = STATE(30),
    [sym_var_declaration] = STATE(30),
    [sym_statement] = STATE(30),
    [sym_expression_statement] = STATE(31),
    [sym_print_statement] = STATE(31),
    [sym_expression] = STATE(13),
    [sym_binary_expression] = STATE(14),
    [sym_unary_expression] = STATE(14),
    [sym_primary_expression] = STATE(14),
    [sym_string] = STATE(9),
    [sym_boolean] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(54),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_val] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(11),
    [anon_sym_print] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_BANG] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(58), 8,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_SLASH,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [24] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_STAR,
    ACTIONS(68), 1,
      anon_sym_SLASH,
    ACTIONS(64), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(60), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(62), 7,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [54] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(72), 8,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_SLASH,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [78] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(76), 8,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_SLASH,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [102] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(80), 8,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_SLASH,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [126] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(84), 8,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_SLASH,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [150] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(88), 8,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_SLASH,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [174] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_STAR,
    ACTIONS(68), 1,
      anon_sym_SLASH,
    ACTIONS(78), 7,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(80), 7,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [202] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_STAR,
    ACTIONS(68), 1,
      anon_sym_SLASH,
    ACTIONS(64), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(90), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(92), 7,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [232] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_STAR,
    ACTIONS(68), 1,
      anon_sym_SLASH,
    ACTIONS(64), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(94), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(96), 7,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [262] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(100), 8,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_SLASH,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [286] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_STAR,
    ACTIONS(68), 1,
      anon_sym_SLASH,
    ACTIONS(64), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(102), 5,
      ts_builtin_sym_end,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(104), 7,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [316] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(108), 8,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_SLASH,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [340] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_number,
    STATE(11), 1,
      sym_expression,
    ACTIONS(7), 2,
      sym_nil,
      sym_identifier,
    ACTIONS(15), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_string,
      sym_boolean,
    STATE(14), 3,
      sym_binary_expression,
      sym_unary_expression,
      sym_primary_expression,
  [377] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_number,
    STATE(16), 1,
      sym_expression,
    ACTIONS(7), 2,
      sym_nil,
      sym_identifier,
    ACTIONS(15), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_string,
      sym_boolean,
    STATE(14), 3,
      sym_binary_expression,
      sym_unary_expression,
      sym_primary_expression,
  [414] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LPAREN,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      sym_number,
    STATE(42), 1,
      sym_expression,
    ACTIONS(110), 2,
      sym_nil,
      sym_identifier,
    ACTIONS(112), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(120), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_string,
      sym_boolean,
    STATE(35), 3,
      sym_binary_expression,
      sym_unary_expression,
      sym_primary_expression,
  [451] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LPAREN,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      sym_number,
    STATE(40), 1,
      sym_expression,
    ACTIONS(110), 2,
      sym_nil,
      sym_identifier,
    ACTIONS(112), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(120), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_string,
      sym_boolean,
    STATE(35), 3,
      sym_binary_expression,
      sym_unary_expression,
      sym_primary_expression,
  [488] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_number,
    STATE(5), 1,
      sym_expression,
    ACTIONS(7), 2,
      sym_nil,
      sym_identifier,
    ACTIONS(15), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_string,
      sym_boolean,
    STATE(14), 3,
      sym_binary_expression,
      sym_unary_expression,
      sym_primary_expression,
  [525] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_number,
    STATE(8), 1,
      sym_expression,
    ACTIONS(7), 2,
      sym_nil,
      sym_identifier,
    ACTIONS(15), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_string,
      sym_boolean,
    STATE(14), 3,
      sym_binary_expression,
      sym_unary_expression,
      sym_primary_expression,
  [562] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LPAREN,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      sym_number,
    STATE(36), 1,
      sym_expression,
    ACTIONS(110), 2,
      sym_nil,
      sym_identifier,
    ACTIONS(112), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(120), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_string,
      sym_boolean,
    STATE(35), 3,
      sym_binary_expression,
      sym_unary_expression,
      sym_primary_expression,
  [599] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_number,
    STATE(15), 1,
      sym_expression,
    ACTIONS(7), 2,
      sym_nil,
      sym_identifier,
    ACTIONS(15), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_string,
      sym_boolean,
    STATE(14), 3,
      sym_binary_expression,
      sym_unary_expression,
      sym_primary_expression,
  [636] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_number,
    STATE(12), 1,
      sym_expression,
    ACTIONS(7), 2,
      sym_nil,
      sym_identifier,
    ACTIONS(15), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_string,
      sym_boolean,
    STATE(14), 3,
      sym_binary_expression,
      sym_unary_expression,
      sym_primary_expression,
  [673] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LPAREN,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      sym_number,
    STATE(41), 1,
      sym_expression,
    ACTIONS(110), 2,
      sym_nil,
      sym_identifier,
    ACTIONS(112), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(120), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_string,
      sym_boolean,
    STATE(35), 3,
      sym_binary_expression,
      sym_unary_expression,
      sym_primary_expression,
  [710] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_LPAREN,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      sym_number,
    STATE(32), 1,
      sym_expression,
    ACTIONS(110), 2,
      sym_nil,
      sym_identifier,
    ACTIONS(112), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(120), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_string,
      sym_boolean,
    STATE(35), 3,
      sym_binary_expression,
      sym_unary_expression,
      sym_primary_expression,
  [747] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_EQ,
    ACTIONS(122), 6,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(124), 7,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [771] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_EQ,
    ACTIONS(128), 6,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(130), 7,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [795] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 6,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(136), 7,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [816] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 6,
      ts_builtin_sym_end,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_number,
    ACTIONS(140), 7,
      anon_sym_val,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [837] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_STAR,
    ACTIONS(146), 1,
      anon_sym_SLASH,
    ACTIONS(148), 1,
      anon_sym_RPAREN,
    ACTIONS(142), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [854] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_SLASH,
    ACTIONS(82), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [867] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      anon_sym_SLASH,
    ACTIONS(86), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [880] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(98), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [893] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_SLASH,
    ACTIONS(106), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [906] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      anon_sym_SLASH,
    ACTIONS(56), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [919] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_SLASH,
    ACTIONS(74), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [932] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_SLASH,
    ACTIONS(70), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [945] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_STAR,
    ACTIONS(146), 1,
      anon_sym_SLASH,
    ACTIONS(78), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
  [960] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_SLASH,
    ACTIONS(78), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
  [973] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_STAR,
    ACTIONS(146), 1,
      anon_sym_SLASH,
    ACTIONS(150), 1,
      anon_sym_RPAREN,
    ACTIONS(142), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [990] = 5,
    ACTIONS(152), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_DQUOTE,
    ACTIONS(156), 1,
      aux_sym_string_token1,
    ACTIONS(159), 1,
      aux_sym_string_token2,
    STATE(43), 1,
      aux_sym_string_repeat1,
  [1006] = 5,
    ACTIONS(152), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_DQUOTE,
    ACTIONS(164), 1,
      aux_sym_string_token1,
    ACTIONS(166), 1,
      aux_sym_string_token2,
    STATE(43), 1,
      aux_sym_string_repeat1,
  [1022] = 5,
    ACTIONS(152), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_DQUOTE,
    ACTIONS(170), 1,
      aux_sym_string_token1,
    ACTIONS(172), 1,
      aux_sym_string_token2,
    STATE(44), 1,
      aux_sym_string_repeat1,
  [1038] = 5,
    ACTIONS(152), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_DQUOTE,
    ACTIONS(176), 1,
      aux_sym_string_token1,
    ACTIONS(178), 1,
      aux_sym_string_token2,
    STATE(47), 1,
      aux_sym_string_repeat1,
  [1054] = 5,
    ACTIONS(152), 1,
      sym_comment,
    ACTIONS(164), 1,
      aux_sym_string_token1,
    ACTIONS(166), 1,
      aux_sym_string_token2,
    ACTIONS(180), 1,
      anon_sym_DQUOTE,
    STATE(43), 1,
      aux_sym_string_repeat1,
  [1070] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      sym_identifier,
  [1077] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
  [1084] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 24,
  [SMALL_STATE(6)] = 54,
  [SMALL_STATE(7)] = 78,
  [SMALL_STATE(8)] = 102,
  [SMALL_STATE(9)] = 126,
  [SMALL_STATE(10)] = 150,
  [SMALL_STATE(11)] = 174,
  [SMALL_STATE(12)] = 202,
  [SMALL_STATE(13)] = 232,
  [SMALL_STATE(14)] = 262,
  [SMALL_STATE(15)] = 286,
  [SMALL_STATE(16)] = 316,
  [SMALL_STATE(17)] = 340,
  [SMALL_STATE(18)] = 377,
  [SMALL_STATE(19)] = 414,
  [SMALL_STATE(20)] = 451,
  [SMALL_STATE(21)] = 488,
  [SMALL_STATE(22)] = 525,
  [SMALL_STATE(23)] = 562,
  [SMALL_STATE(24)] = 599,
  [SMALL_STATE(25)] = 636,
  [SMALL_STATE(26)] = 673,
  [SMALL_STATE(27)] = 710,
  [SMALL_STATE(28)] = 747,
  [SMALL_STATE(29)] = 771,
  [SMALL_STATE(30)] = 795,
  [SMALL_STATE(31)] = 816,
  [SMALL_STATE(32)] = 837,
  [SMALL_STATE(33)] = 854,
  [SMALL_STATE(34)] = 867,
  [SMALL_STATE(35)] = 880,
  [SMALL_STATE(36)] = 893,
  [SMALL_STATE(37)] = 906,
  [SMALL_STATE(38)] = 919,
  [SMALL_STATE(39)] = 932,
  [SMALL_STATE(40)] = 945,
  [SMALL_STATE(41)] = 960,
  [SMALL_STATE(42)] = 973,
  [SMALL_STATE(43)] = 990,
  [SMALL_STATE(44)] = 1006,
  [SMALL_STATE(45)] = 1022,
  [SMALL_STATE(46)] = 1038,
  [SMALL_STATE(47)] = 1054,
  [SMALL_STATE(48)] = 1070,
  [SMALL_STATE(49)] = 1077,
  [SMALL_STATE(50)] = 1084,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(9),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(48),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(50),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(21),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(18),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(27),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(45),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(9),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(10),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_statement, 2),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_print_statement, 2),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expression, 3),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_expression, 3),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expression, 1),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_expression, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_declaration, 4, .production_id = 3),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_declaration, 4, .production_id = 3),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_val_declaration, 4, .production_id = 3),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_val_declaration, 4, .production_id = 3),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_declaration, 2, .production_id = 1),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_declaration, 2, .production_id = 1),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_val_declaration, 2, .production_id = 1),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_val_declaration, 2, .production_id = 1),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 1),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 1),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(43),
  [159] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(43),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [184] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_neon(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
