impl OpCode {
    #[inline(always)]
    pub(crate) fn from_u8(value: u8) -> Option<OpCode> {
        match value {
            v if v == OpCode::Return as u8 => Some(OpCode::Return),
            v if v == OpCode::Constant as u8 => Some(OpCode::Constant),
            v if v == OpCode::Constant2 as u8 => Some(OpCode::Constant2),
            v if v == OpCode::Constant4 as u8 => Some(OpCode::Constant4),
            v if v == OpCode::Negate as u8 => Some(OpCode::Negate),
            v if v == OpCode::Add as u8 => Some(OpCode::Add),
            v if v == OpCode::Subtract as u8 => Some(OpCode::Subtract),
            v if v == OpCode::Multiply as u8 => Some(OpCode::Multiply),
            v if v == OpCode::Divide as u8 => Some(OpCode::Divide),
            v if v == OpCode::Modulo as u8 => Some(OpCode::Modulo),
            v if v == OpCode::Exponent as u8 => Some(OpCode::Exponent),
            v if v == OpCode::Nil as u8 => Some(OpCode::Nil),
            v if v == OpCode::True as u8 => Some(OpCode::True),
            v if v == OpCode::False as u8 => Some(OpCode::False),
            v if v == OpCode::Equal as u8 => Some(OpCode::Equal),
            v if v == OpCode::Greater as u8 => Some(OpCode::Greater),
            v if v == OpCode::GreaterEqual as u8 => Some(OpCode::GreaterEqual),
            v if v == OpCode::Less as u8 => Some(OpCode::Less),
            v if v == OpCode::LessEqual as u8 => Some(OpCode::LessEqual),
            v if v == OpCode::Not as u8 => Some(OpCode::Not),
            v if v == OpCode::String as u8 => Some(OpCode::String),
            v if v == OpCode::String2 as u8 => Some(OpCode::String2),
            v if v == OpCode::String4 as u8 => Some(OpCode::String4),
            v if v == OpCode::Pop as u8 => Some(OpCode::Pop),
            v if v == OpCode::SetLocal as u8 => Some(OpCode::SetLocal),
            v if v == OpCode::SetLocal2 as u8 => Some(OpCode::SetLocal2),
            v if v == OpCode::SetLocal4 as u8 => Some(OpCode::SetLocal4),
            v if v == OpCode::GetLocal as u8 => Some(OpCode::GetLocal),
            v if v == OpCode::GetLocal2 as u8 => Some(OpCode::GetLocal2),
            v if v == OpCode::GetLocal4 as u8 => Some(OpCode::GetLocal4),
            v if v == OpCode::JumpIfFalse as u8 => Some(OpCode::JumpIfFalse),
            v if v == OpCode::Jump as u8 => Some(OpCode::Jump),
            v if v == OpCode::Loop as u8 => Some(OpCode::Loop),
            v if v == OpCode::Call as u8 => Some(OpCode::Call),
            v if v == OpCode::GetBuiltin as u8 => Some(OpCode::GetBuiltin),
            v if v == OpCode::GetBuiltin2 as u8 => Some(OpCode::GetBuiltin2),
            v if v == OpCode::GetBuiltin4 as u8 => Some(OpCode::GetBuiltin4),
            v if v == OpCode::GetGlobal as u8 => Some(OpCode::GetGlobal),
            v if v == OpCode::GetGlobal2 as u8 => Some(OpCode::GetGlobal2),
            v if v == OpCode::GetGlobal4 as u8 => Some(OpCode::GetGlobal4),
            v if v == OpCode::SetGlobal as u8 => Some(OpCode::SetGlobal),
            v if v == OpCode::SetGlobal2 as u8 => Some(OpCode::SetGlobal2),
            v if v == OpCode::SetGlobal4 as u8 => Some(OpCode::SetGlobal4),
            v if v == OpCode::GetField as u8 => Some(OpCode::GetField),
            v if v == OpCode::GetField2 as u8 => Some(OpCode::GetField2),
            v if v == OpCode::GetField4 as u8 => Some(OpCode::GetField4),
            v if v == OpCode::SetField as u8 => Some(OpCode::SetField),
            v if v == OpCode::SetField2 as u8 => Some(OpCode::SetField2),
            v if v == OpCode::SetField4 as u8 => Some(OpCode::SetField4),
            v if v == OpCode::CreateMap as u8 => Some(OpCode::CreateMap),
            v if v == OpCode::CreateArray as u8 => Some(OpCode::CreateArray),
            v if v == OpCode::CreateSet as u8 => Some(OpCode::CreateSet),
            v if v == OpCode::GetIndex as u8 => Some(OpCode::GetIndex),
            v if v == OpCode::SetIndex as u8 => Some(OpCode::SetIndex),
            v if v == OpCode::GetIterator as u8 => Some(OpCode::GetIterator),
            v if v == OpCode::IteratorNext as u8 => Some(OpCode::IteratorNext),
            v if v == OpCode::IteratorDone as u8 => Some(OpCode::IteratorDone),
            v if v == OpCode::PopIterator as u8 => Some(OpCode::PopIterator),
            v if v == OpCode::CreateRange as u8 => Some(OpCode::CreateRange),
            v if v == OpCode::ToString as u8 => Some(OpCode::ToString),
            v if v == OpCode::BitwiseAnd as u8 => Some(OpCode::BitwiseAnd),
            v if v == OpCode::BitwiseOr as u8 => Some(OpCode::BitwiseOr),
            v if v == OpCode::BitwiseXor as u8 => Some(OpCode::BitwiseXor),
            v if v == OpCode::BitwiseNot as u8 => Some(OpCode::BitwiseNot),
            v if v == OpCode::LeftShift as u8 => Some(OpCode::LeftShift),
            v if v == OpCode::RightShift as u8 => Some(OpCode::RightShift),
            v if v == OpCode::Closure as u8 => Some(OpCode::Closure),
            v if v == OpCode::Closure2 as u8 => Some(OpCode::Closure2),
            v if v == OpCode::Closure4 as u8 => Some(OpCode::Closure4),
            v if v == OpCode::GetUpvalue as u8 => Some(OpCode::GetUpvalue),
            v if v == OpCode::GetUpvalue2 as u8 => Some(OpCode::GetUpvalue2),
            v if v == OpCode::GetUpvalue4 as u8 => Some(OpCode::GetUpvalue4),
            v if v == OpCode::SetUpvalue as u8 => Some(OpCode::SetUpvalue),
            v if v == OpCode::SetUpvalue2 as u8 => Some(OpCode::SetUpvalue2),
            v if v == OpCode::SetUpvalue4 as u8 => Some(OpCode::SetUpvalue4),
            v if v == OpCode::CloseUpvalue as u8 => Some(OpCode::CloseUpvalue),
            v if v == OpCode::CloseUpvalueInPlace as u8 => Some(OpCode::CloseUpvalueInPlace),
            v if v == OpCode::DefineMethod as u8 => Some(OpCode::DefineMethod),
            v if v == OpCode::CheckInitialized as u8 => Some(OpCode::CheckInitialized),
            _ => None,
        }
    }
}

#[repr(u8)]
#[derive(Debug, PartialEq)]
#[allow(dead_code)]
pub(crate) enum OpCode {
    Return = 0x00,
    Constant,
    Constant2,
    Constant4,
    Negate,
    Add,
    Subtract,
    Multiply,
    Divide,
    Modulo,
    Exponent,
    Nil,
    True,
    False,
    Equal,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    Not,
    String,
    String2,
    String4,
    Pop,
    SetLocal,
    SetLocal2,
    SetLocal4,
    GetLocal,
    GetLocal2,
    GetLocal4,
    JumpIfFalse,
    Jump,
    Loop,
    Call,
    GetBuiltin,
    GetBuiltin2,
    GetBuiltin4,
    GetGlobal,
    GetGlobal2,
    GetGlobal4,
    SetGlobal,
    SetGlobal2,
    SetGlobal4,
    GetField,
    GetField2,
    GetField4,
    SetField,
    SetField2,
    SetField4,

    CreateMap,
    CreateArray,
    CreateSet,
    GetIndex,
    SetIndex,
    GetIterator,
    IteratorNext,
    IteratorDone,
    PopIterator,
    CreateRange,
    ToString,

    // Bitwise operations
    BitwiseAnd,
    BitwiseOr,
    BitwiseXor,
    BitwiseNot,
    LeftShift,
    RightShift,

    /// Wraps a function constant in a closure: reads a function constant
    /// index, then an upvalue count and that many (is_local, index) pairs
    /// describing how to fill the closure's upvalue array.
    Closure,
    Closure2,
    Closure4,
    GetUpvalue,
    GetUpvalue2,
    GetUpvalue4,
    SetUpvalue,
    SetUpvalue2,
    SetUpvalue4,
    /// Closes the upvalue (if any) pointing at the top-of-stack slot, then
    /// pops it, so a captured local's value survives its scope exiting.
    CloseUpvalue,
    /// Closes the upvalue on the top-of-stack slot without popping it.
    CloseUpvalueInPlace,
    /// Pops a closure and registers it as a method under a type name and
    /// method name (both read as fixed 32-bit string indices).
    DefineMethod,
    /// Peeks the top of the stack and errors if it holds a hoisted
    /// declaration's uninitialized sentinel; otherwise a no-op.
    CheckInitialized,
}
