name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install components
        run: rustup component add rustfmt clippy
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Check Neon script formatting
        run: cargo run -q -- fmt --check tests/scripts tests/modules tests/modules_must_fail benches examples
